[versions]
json = "20240205"
reactor-netty = "1.1.16"

[libraries]
json = { module = "org.json:json", version.ref = "json" }
reactor-netty = { module = "io.projectreactor.netty:reactor-netty", version.ref = "reactor-netty" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.22" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
metadata = { id = "io.github.sgtsilvio.gradle.metadata", version = "0.5.0" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
